version: '3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doclickDB
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - common-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doclick_container
    depends_on:
      - mysql_db
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: local
      MYSQL_DB_HOST: mysql_db
      MYSQL_DB_NAME: doclickDB
      MYSQL_DB_USER: root
      MYSQL_DB_PASS: root
    links:
      - mysql_db
    networks:
      - common-network

networks:
  common-network:
    driver: bridge