spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${MYSQL_DB_HOST}:3306/${MYSQL_DB_NAME}
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASS}
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8